//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 DNAssist.rc 使用
//
#define IDR_strTYPE_CNTR_IP             7
#define ID_INDICATOR_SEL                101
#define ID_INDICATOR_POS                102
#define ID_INDICATOR_SEQTYPE            103
#define ID_INDICATOR_FORM               104
#define IDP_OLE_INIT_FAILED             126
#define IDP_FAILED_TO_CREATE            127
#define IDR_MAINFRAME                   128
#define IDR_seqTYPE                     129
#define IDR_txtTYPE                     130
#define IDR_strTYPE                     131
#define IDR_fasTYPE                     132
#define IDR_gcgTYPE                     133
#define IDR_gbkTYPE                     134
#define IDR_dnaTYPE_CNTR_IP             135
#define IDR_plotTYPE                    136
#define IDR_viewTYPE                    137
#define ID_WINDOW_MANAGER               138
#define IDR_TITLE                       141
#define IDD_FONTPROPERTYPAGE            310
#define IDD_ABOUTBOX                    313
#define IDD_PROTEINPROPERTIES           314
#define IDD_ADDENZYME                   315
#define IDD_ALIGN                       316
#define IDD_ALIGN_GENERAL               318
#define IDD_ALIGN_DNA                   319
#define IDD_ALIGN_PROTEIN               320
#define IDD_ALIGN_COLOR                 324
#define IDD_EDITOR_DIRECTORIES          326
#define IDD_FINDDLG                     329
#define IDD_FINDORF                     330
#define IDD_FINDPATTERN                 333
#define IDD_SELECTGENBANKSEQUENCE       335
#define IDD_HELIXPARAM                  336
#define IDD_HELIXPARAMS                 338
#define IDD_FACTOR                      339
#define IDD_SPECIES                     340
#define IDD_GROUP                       341
#define IDD_KINGDOM                     342
#define IDD_TRANSFAC_DISPLAY            343
#define IDD_TRANSFAC_OPTIONS            353
#define IDD_PROGRESSDIALOG              355
#define IDD_PROPERTIES                  356
#define IDD_RESTENDO                    357
#define IDD_SEQUENCETYPE                359
#define IDD_ANALYSISOPTIONS             360
#define IDD_PRINTFORMAT                 361
#define IDD_CODON                       362
#define IDD_OUTPUT                      363
#define IDD_TRANSFACOPTIONS             380
#define IDD_TRANSFACSEARCH              381
#define IDI_QUERY                       384
#define IDD_UNDO                        390
#define IDD_SHOWAS                      391
#define IDD_PRINTFONT                   392
#define IDD_INPUTDIALOG                 393
#define IDD_EDITOR_LINELENGTH           395
#define ICO_DNA1                        396
#define ICO_DNA2                        397
#define ICO_RNA1                        398
#define ICO_RNA2                        399
#define ICO_P1                          400
#define ICO_P2                          401
#define ICO_D1                          402
#define ICO_D2                          403
#define IDC_COMBO1                      1009
#define IDC_STRIKEOUT                   0x0410
#define IDC_UNDERLINE                   0x0411
#define grp1                            0x0430
#define grp2                            0x0431
#define stc1                            0x0440
#define stc2                            0x0441
#define stc3                            0x0442
#define IDC_SAMPLE                      0x0444
#define IDC_FONT                        0x0470
#define IDC_STYLE                       0x0471
#define IDC_FONTSIZE                    0x0472
#define IDD_FONTPAGE                    1543
#define IDB_ABOUT                       2000
#define IDC_A                           2001
#define IDC_A280                        2002
#define IDC_ABOUT_COPYRIGHT             2003
#define IDC_ABOUT_OWNER                 2004
#define IDC_ABOUT_VERSION               2005
#define IDC_ADDENZYME                   2006
#define IDC_ABOUT_OWNER2                2006
#define IDC_ADDENZYMELOWER              2007
#define IDC_ADDENZYMENAME               2008
#define IDC_ADDENZYMESITE               2009
#define IDC_ADDENZYMEUPPER              2010
#define IDC_ALIGNTEXT1                  2011
#define IDC_ALIGN_DEFAULTS              2012
#define IDC_ALIGN_DEFAULTS_PROTEIN      2013
#define IDC_ALIGN_DEFAULT_COLOR         2014
#define IDC_ALIGN_DEFAULT_DNA           2015
#define IDC_ALIGN_SEQUENCES             2016
#define IDC_ANNEAL                      2018
#define IDC_ANTIGENICITY                2019
#define IDC_APLUSTLABEL                 2020
#define IDC_A_MG_DOUBLE                 2021
#define IDC_A_MG_SINGLE                 2022
#define IDC_A_MOLE_DOUBLE               2023
#define IDC_A_MOL_SINGLE                2024
#define IDC_AplusT                      2025
#define IDC_BLOCKGAPSIZE                2026
#define IDC_BLOCKSIZE                   2027
#define IDC_BROWSE                      2028
#define IDC_C                           2033
#define IDC_CANCEL                      2034
#define IDC_CHARGEATPH                  2035
#define IDC_CODONFILES                  2036
#define IDC_CODONPATH                   2037
#define IDC_CODONPATHBROWSE             2038
#define IDC_CONSERVED_BACKGROUND        2039
#define IDC_CONSERVED_FOREGROUND        2040
#define IDC_CONSERVED_PERCENTAGE        2041
#define IDC_DELAY_DIVERGENT_SEQUENCES   2042
#define IDC_DISPLAYALL                  2043
#define IDC_DISPLAYCONTINOUSSEQUENCE    2044
#define IDC_DISPLAYGRAPHIC              2045
#define IDC_DISPLAYLINES                2046
#define IDC_DISPLAYSEQUENCEBLOCKS       2047
#define IDC_DISPLAYSEQUENCELIST         2048
#define IDC_DISPLAYTABLES               2049
#define IDC_DISPLAYWATSONANDCRICK       2050
#define IDC_DISPLAYWATSONONLY           2051
#define IDC_DNA_TRANSITION_WEIGHT       2052
#define IDC_DNA_WEIGHT_MATRIX           2053
#define IDC_E280                        2054
#define IDC_EDITOR_LINELENGTH           2055
#define IDC_EDITOR_SEQUENCE             2056
#define IDC_EDITOR_SEQUENCES_BROWSE     2057
#define IDC_ENDSEARCH                   2062
#define IDC_END_GAP_SEPARATION          2063
#define IDC_ENTHALPY                    2064
#define IDC_ENTROPY                     2065
#define IDC_ENZYMELIST                  2066
#define IDC_FACENAME                    2067
#define IDC_FACESIZE                    2068
#define IDC_FACTOR                      2069
#define IDC_FIND                        2072
#define IDC_FINDAGAIN                   2073
#define IDC_FINDNEXTORF                 2074
#define IDC_FINDORF                     2075
#define IDC_FINDPATTERN                 2076
#define IDC_FINDPATTERN_CANCEL          2077
#define IDC_FINDPATTERN_FIND            2078
#define IDC_FINDPATTERN_FINDNEXT        2079
#define IDC_FINDPATTERN_GAP             2080
#define IDC_FINDPATTERN_MISMATCH        2081
#define IDC_FINDPATTERN_NUCLEOTIDE      2082
#define IDC_FINDPATTERN_SECONDSTRAND    2083
#define IDC_FINDTEXT                    2084
#define IDC_FORMATALL                   2085
#define IDC_FORMATGRAPHIC               2086
#define IDC_FORMATLINE                  2087
#define IDC_FORMATSEQUENCE              2088
#define IDC_FORMATTABLE                 2089
#define IDC_G                           2090
#define IDC_GAPSIZE                     2091
#define IDC_GAP_EXTENSION_PENALTY       2092
#define IDC_GAP_OPENING_PENALTY         2093
#define IDC_GAP_SEPARATION_DISTANCE     2094
#define IDC_GPSEL                       2095
#define IDC_GPUNIQUE                    2096
#define IDC_GPUNIQUESEL                 2097
#define IDC_GROUP                       2098
#define IDC_GplusC                      2099
#define IDC_HYDROPHILICITY              2100
#define IDC_HYDROPHILIC_RESIDUES        2101
#define IDC_HYDROPHOBICITY              2102
#define IDC_HYDROPHYLIC_PENALTY         2103
#define IDC_IDENTICAL_BACKGROUND        2104
#define IDC_IDENTICAL_FOREGROUND        2105
#define IDC_IDENTICAL_PERCENTAGE        2106
#define IDC_KINGDOM                     2107
#define IDC_LENGTH                      2108
#define IDC_MELT                        2109
#define IDC_MISMATCH                    2110
#define IDC_MOLE_A                      2111
#define IDC_MOLE_C                      2112
#define IDC_MOLE_D                      2113
#define IDC_MOLE_E                      2114
#define IDC_MOLE_F                      2115
#define IDC_MOLE_G                      2116
#define IDC_MOLE_H                      2117
#define IDC_MOLE_I                      2118
#define IDC_MOLE_K                      2119
#define IDC_MOLE_L                      2120
#define IDC_MOLE_M                      2121
#define IDC_MOLE_N                      2122
#define IDC_MOLE_P                      2123
#define IDC_MOLE_Q                      2124
#define IDC_MOLE_R                      2125
#define IDC_MOLE_S                      2126
#define IDC_MOLE_T                      2127
#define IDC_MOLE_V                      2128
#define IDC_MOLE_W                      2129
#define IDC_MOLE_Y                      2130
#define IDC_MOLWEIGHTDOUBLE             2131
#define IDC_MOLWEIGHTSINGLE             2132
#define IDC_MW                          2133
#define IDC_NUMBERABOVESEQUENCE         2134
#define IDC_NUMBERBELOW                 2135
#define IDC_NUMBERGAPS                  2136
#define IDC_NUMBERRIGHT                 2137
#define IDC_ORFSCOPEFROMCURSOR          2138
#define IDC_ORFSCOPEGLOBAL              2139
#define IDC_OSVERSION                   2140
#define IDC_OUTPUTNEWWINDOW             2141
#define IDC_OUTPUTREPLACE               2142
#define IDC_PI                          2143
#define IDC_PROGRESSBAR1                2144
#define IDC_PROGRESSMESSAGE1            2145
#define IDC_PROGRESSMESSAGE2            2146
#define IDC_PROTEINLENGTH               2147
#define IDC_PROTEIN_WEIGHT_MATRIX       2148
#define IDC_QUERY                       2149
#define IDC_REMOVEENZYME                2150
#define IDC_RESIDUE_SPECIFIC_PENALTY    2151
#define IDC_RES_A                       2152
#define IDC_RES_C                       2153
#define IDC_RES_D                       2154
#define IDC_RES_E                       2155
#define IDC_RES_F                       2156
#define IDC_RES_G                       2157
#define IDC_RES_H                       2158
#define IDC_RES_I                       2159
#define IDC_RES_K                       2160
#define IDC_RES_L                       2161
#define IDC_RES_M                       2162
#define IDC_RES_N                       2163
#define IDC_RES_P                       2164
#define IDC_RES_Q                       2165
#define IDC_RES_R                       2166
#define IDC_RES_S                       2167
#define IDC_RES_T                       2168
#define IDC_RES_V                       2169
#define IDC_RES_W                       2170
#define IDC_RES_Y                       2171
#define IDC_SAVEENZYMELIST              2172
#define IDC_SCOPEFROMCURSOR             2173
#define IDC_SCOPEGLOBAL                 2174
#define IDC_SEARCHWITHALL               2175
#define IDC_SEARCHWITHSELECTION         2176
#define IDC_SELECTSEQUENCE              2177
#define IDC_SEQUENCE                    2178
#define IDC_SEQUENCETYPE                2179
#define IDC_SLALL                       2180
#define IDC_SLBLUNT                     2181
#define IDC_SLEIGHTCUTTER               2182
#define IDC_SLFIVEPRIME                 2183
#define IDC_SLFOURCUTTER                2184
#define IDC_SLOUTSIDE                   2185
#define IDC_SLPALINDROME                2186
#define IDC_SLSELECTION                 2187
#define IDC_SLSIXCUTTER                 2188
#define IDC_SLTHREEPRIME                2189
#define IDC_SLWHOLESET                  2190
#define IDC_SORT                        2191
#define IDC_SORT_BY                     2192
#define IDC_SPECIES                     2193
#define IDC_T                           2196
#define IDC_TLABEL                      2197
#define IDC_TRANSFAC_ALLFORMATS         2198
#define IDC_TRANSFAC_GRAPHICMAP         2199
#define IDC_TRANSFAC_SELECTALL          2200
#define IDC_TRANSFAC_SELECTION          2201
#define IDC_TRANSFAC_SEQUENCELIST       2202
#define IDC_TRANSFAC_TABLE              2203
#define IDC_TRANSFAC_UNIQUE             2204
#define IDC_TRANSFAC_UNIQUEANDSEL       2205
#define IDC_UNDOLEVELS                  2206
#define IDC_USERCANCEL                  2207
#define IDC_WHENMATRIX                  2208
#define ID_INPUT                        2212
#define ID_PROMPT                       2213
#define IDC_WARNING                     2214
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_EDIT_CHANGECASE              32772
#define ID_CHANGECASE_UPPERCASE         32773
#define ID_CHANGECASE_LOWERCASE         32774
#define ID_NEW_DNA                      32775
#define ID_NEW_RNA                      32776
#define ID_NEW_PROTEIN                  32777
#define ID_NEW_DEGENERATEDNA            32778
#define ID_CONVERT_CIRCULARIZE          32779
#define ID_CONVERT_LINEARIZE            32780
#define ID_CONVERT_REVERSE              32781
#define ID_GET_SEQ_TYPE                 32782
#define ID_CONVERT_REVERSETRANSLATE     32787
#define ID_ANALYZE_TRANSLATE            32788
#define ID_TRANSLATE_1PHASE             32789
#define ID_TRANSLATE_3PHASE             32790
#define ID_TRANSLATE_6PHASE             32791
#define ID_ANALYZE_FINDORFS             32792
#define ID_ANALYZE_FINDPATTERN          32793
#define ID_ANALYZE_LIST                 32794
#define ID_ANALYZE_PROPERTIES           32795
#define ID_PROPERTIES_PHYSICOCHEMICAL   32796
#define ID_PROPERTIES_HYDROPHOBICITY    32797
#define ID_PROPERTIES_HYDROPHILICITY    32798
#define ID_PROPERTIES_ANTIGENICITY      32799
#define ID_ANALYZE_RESTRICTIONMAPPING   32800
#define ID_ANALYZE_TRANSCRIPTIONFACTORS 32801
#define ID_ANALYZE_NUCLEOSOMEPOSITIONS  32802
#define ID_ANALYZE_ALIGN                32803
#define ID_ANALYZE_RANDOMIZE            32804
#define ID_ANALYZE_VISITWWW             32805
#define ID_VISITWWW_DNASSIST            32806
#define ID_VISITWWW_ENTREZ              32807
#define ID_VISITWWW_BLAST               32808
#define ID_OPTIONS_EDITOR               32809
#define ID_OPTIONS_ANALYSIS             32810
#define ID_OPTIONS_RESULTDISPLAY        32811
#define ID_OPTIONS_TRANSCRIPTIONFACTORS 32812
#define ID_OPTIONS_ALIGNMENT            32813
#define ID_WINDOW_CLOSEALL              32814
#define ID_HELP_ENTREZ                  32815
#define ID_HELP_BLAST                   32816
#define ID_HELP_CONTENTS                32818
#define ID_CONVERT_RNA2DNA              32825
#define ID_CONVERT_DNA2PRO              32826
#define ID_CONVERT_RNA2PRO              32827
#define ID_CONVERT_DNA2RNA              32828
#define ID_BUTTON32829                  32829
#define IDS_ONEPHASETRANSLATION         33001
#define IDS_THREEPHASETRANSLATION       33002
#define IDS_SIXPHASETRANSLATION         33003
#define IDS_RESTRICTIONMAP              33004
#define IDS_TRANSCRIPTIONFACTORMAP      33005
#define IDS_DREWPLOT                    33006
#define IDS_LIST                        33007
#define IDS_FINDPATTERN                 33008
#define IDS_INITIALIZINGCODONTABLE      33009
#define IDS_INITIALIZINGTRANSCRIPTIONFACTORDATABASE 33010
#define IDS_INITIALIZINGRESTRICTIONDATABASE 33011
#define IDS_APPLICATIONNAME             33012
#define IDS_SEARCHONLYSELECTION         33013
#define IDS_TRANSCRIPTIONFACTORMANAGER  33014
#define IDS_VERSIONNUMBER               33015
#define IDS_KINGDOMHEADER               33016
#define IDS_SPECIESHEADER               33017
#define IDS_FACTORHEADER                33018
#define IDS_SEQUENCEHEADER              33019
#define IDS_MATRIXHEADER                33020
#define IDS_DATAHEADER                  33021
#define IDS_USEMATRIX_NEVER             33022
#define IDS_USEMATRIX_ALSOWHENAVAILABLE 33023
#define IDS_USEMATRIX_EXCLUSIVELYWHENAVAILABLE 33024
#define IDS_USEMATRIX_EXCLUSIVELY       33025
#define IDS_READFACTORFILE              33026
#define IDS_READSITEFILE                33027
#define IDS_READNATIVEFILE              33028
#define IDS_INITIALIZEDATABASE          33029
#define IDS_FOUNDNEWTRANSFAC            33030
#define IDS_THISMAYTAKEAFEWMINUTES      33031
#define IDS_WRITINGDATABASE             33032
#define IDS_CONVERTINGDATABASE          33033
#define IDS_WRITING_                    33034
#define IDS_WRITINGHEADERSECTION        33035
#define IDS_WRITINGDATASECTION          33036
#define IDS_NOSELECTEDFACTORS           33037
#define IDS_REQUIREMORETHANTWO          33038
#define IDS_READMATRIXFILE              33039
#define IDS_MATRIXNEVER                 33040
#define IDS_MATRIXASWELL                33041
#define IDS_MATRIXWHENAVAILABLE         33042
#define IDS_MATRIXEXCLUSIVE             33043
#define IDS_GRAPHIC                     33044
#define IDS_TABLE                       33045
#define IDS_FILEWRITEFAILED             33046
#define IDS_VERSION                     33047
#define IDS_COPYRIGHT                   33048
#define IDS_OWNER                       33049
#define IDS_NOTREGISTERED               33050
#define IDS_NODELETEFILE                33051
#define IDS_NOTPROPERLYINSTALLED        33052
#define IDS_RUNSETUP                    33053
#define IDS_REGISTRYCORRUPTED           33054
#define IDS_FINDRESTRICTIONENZYMEDIRECTORY 33055
#define IDS_CANNOTDORESTRICTIONANALYSIS 33056
#define IDS_HELPFILE                    33057

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        400
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
