; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=DNAssist
AppVersion=3.01
AppVerName=DNAssist 3.01
AppPublisher=Miller Cy Chan
AppPublisherURL=http://dnassist.co.nf/
AppSupportURL=http://ichiba.geocities.jp/chan_ykf/
AppUpdatesURL=http://dnassist.co.nf/
ArchitecturesInstallIn64BitMode=x64
ArchitecturesAllowed=x64
DefaultDirName={pf}\DNAssist
DefaultGroupName=DNAssist
DisableProgramGroupPage=yes
OutputBaseFilename=DNAssist3_x64
OutputDir=..\..\Release
SolidCompression=yes
VersionInfoDescription=Dnassist Setup
VersionInfoVersion=3.0.1

[Tasks]
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\x64\Release\DNAssist.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\DNAssist\res\vcomp140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\sqlite3\sqlite3-64.dll"; DestDir: "{app}"; DestName: "sqlite3.dll"; Flags: ignoreversion
Source: "..\..\x64\Release\Transfac.db"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\x64\Release\Codon\*"; DestDir: "{app}\Codon"; Flags: ignoreversion recursesubdirs
Source: "..\..\x64\Release\Enzymes\*"; DestDir: "{app}\Enzymes"; Flags: ignoreversion recursesubdirs
Source: "..\..\x64\Release\Help\*"; DestDir: "{app}\Help"; Flags: ignoreversion recursesubdirs
Source: "..\..\x64\Release\Sequences\*"; DestDir: "{app}\Sequences"; Flags: ignoreversion recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\DNAssist"; Filename: "{app}\DNAssist.exe"
Name: "{group}\{cm:UninstallProgram,DNAssist}"; Filename: "{uninstallexe}"
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\DNAssist"; Filename: "{app}\DNAssist.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\DNAssist.exe"; Description: "{cm:LaunchProgram,DNAssist}"; Flags: nowait runascurrentuser postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\DNAssist"; Flags: deletekey
Root: HKCU; Subkey: "Software\DNAssist"; Flags: uninsdeletekey
