; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=DNAssist
AppVersion=3.02
AppVerName=DNAssist 3.02
AppPublisher=Miller Cy Chan
AppPublisherURL=http://dnassist.co.nf/
AppSupportURL=http://ichiba.geocities.jp/chan_ykf/
AppUpdatesURL=http://dnassist.co.nf/
DefaultDirName={pf}\DNAssist
DefaultGroupName=DNAssist
DisableProgramGroupPage=yes
OutputBaseFilename=DNAssist3
OutputDir=..\..\Release
SolidCompression=yes
UninstallDisplayIcon={app}\DNAssist.exe
VersionInfoDescription=Dnassist Setup
VersionInfoVersion=3.0.2

[Tasks]
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\Release\DNAssist.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\sqlite3\sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\x64\Release\Transfac.db"; DestDir: "{app}"; Flags: onlyifdoesntexist
Source: "..\..\x64\Release\Codon\*"; DestDir: "{app}\Codon"; Flags: onlyifdoesntexist recursesubdirs
Source: "..\..\x64\Release\Enzymes\*"; DestDir: "{app}\Enzymes"; Flags: onlyifdoesntexist recursesubdirs
Source: "..\..\x64\Release\Help\*"; DestDir: "{app}\Help"; Flags: onlyifdoesntexist recursesubdirs
Source: "..\..\x64\Release\Sequences\*"; DestDir: "{app}\Sequences"; Flags: onlyifdoesntexist recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\DNAssist"; Filename: "{app}\DNAssist.exe"
Name: "{group}\{cm:UninstallProgram,DNAssist}"; Filename: "{uninstallexe}"
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\DNAssist"; Filename: "{app}\DNAssist.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\DNAssist.exe"; Description: "{cm:LaunchProgram,DNAssist}"; Flags: nowait runascurrentuser postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\DNAssist"; Flags: deletekey
Root: HKCU; Subkey: "Software\DNAssist"; Flags: uninsdeletekey
